In [2]:
%matplotlib inline
import matplotlib.pyplot as plt

# 2.1. Numpy ndarray - создание

Numpy - библиотека для векторизованных вычислений в Python'e. Написана на C. Основной объект в numpy - nddarray, который располагается напрерывно в памяти и позволяет производить быстрые вычисления.

In [3]:
import numpy as np

In [4]:
%%timeit
a = np.array(list(range(10000)))
a * a

828 µs ± 1.57 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
%%timeit
a = np.array(list(range(10000)))
a ** 2

834 µs ± 3.22 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
%%timeit
a = np.arange(10000)
a ** 2

14.6 µs ± 138 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [21]:
np.array([10])

array([10])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Создание массива

In [29]:
a = np.array([1, 2, 3, 4])

In [30]:
a

array([1, 2, 3, 4])

In [31]:
a.shape

(4,)

Shape - кортеж, который указывает число элементов в каждом измерении. 

In [64]:
a = np.array([[[1, 2], [3, 4]], 
             [[12, 23], [34, 4]],
              [[2, 21], [54, 44]] ])

In [46]:
a.shape

(3, 2, 2)

In [61]:
a = np.array([1, 2, 3])

In [62]:
a

array([1, 2, 3])

In [58]:
np.arange(start=10, stop=-1, step=-2)

array([10,  8,  6,  4,  2,  0])

In [53]:
a.reshape(2, 2, 3)

array([[[ 1,  2,  3],
        [ 4, 12, 23]],

       [[34,  4,  2],
        [21, 54, 44]]])

In [34]:
a.shape

(2, 2)

In [36]:
a.dtype

dtype('int64')

In [37]:
a.itemsize

8

In [38]:
a.nbytes

32

In [39]:
a

array([[1, 2],
       [3, 4]])

In [66]:
a.reshape(4, -1)

array([[ 1,  2,  3],
       [ 4, 12, 23],
       [34,  4,  2],
       [21, 54, 44]])

In [67]:
a.reshape(1, 3)

ValueError: cannot reshape array of size 12 into shape (1,3)

In [68]:
a.reshape(4, -1)

array([[ 1,  2,  3],
       [ 4, 12, 23],
       [34,  4,  2],
       [21, 54, 44]])

In [70]:
a.reshape(1, -1)

array([[ 1,  2,  3,  4, 12, 23, 34,  4,  2, 21, 54, 44]])

In [69]:
a.reshape(1, -1).shape

(1, 12)

При желании, можно использовать np.size(np.object) и np.shape(np.object):

In [71]:
np.size(a)

12

In [72]:
np.shape(a)

(3, 2, 2)

In [73]:
a.size

12

In [74]:
a.shape

(3, 2, 2)

При необходимости, не стоит принебрегать встроенной справкой:

Shift + tab*(1, 2, 4)

In [ ]:
np.array()

И специальными функциями numpy:

In [77]:
a

array([[[ 1,  2],
        [ 3,  4]],

       [[12, 23],
        [34,  4]],

       [[ 2, 21],
        [54, 44]]])

In [78]:
np.zeros_like(a)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [76]:
np.lookfor('create array of zeros')

Search results for 'create array of zeros'
------------------------------------------
numpy.zeros_like
    Return an array of zeros with the same shape and type as a given array.
numpy.array
    Create an array.
numpy.ndarray
    ndarray(shape, dtype=float, buffer=None, offset=0,
numpy.ones_like
    Return an array of ones with the same shape and type as a given array.
numpy.diag_indices
    Return the indices to access the main diagonal of an array.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.pad
    Pad an array.
numpy.nditer
    Efficient multi-dimensional iterator object to iterate over arrays.
numpy.full_like
    Return a full array with the same shape and type as a given array.
numpy.empty_like
    Return a new array with the same shape and type as a given array.
numpy.left_shift
    Shift the bits of an integer to the left.
numpy.fft.ifft
    Compute the one-dimensional inverse discrete Fourier Transform.
numpy.fft.ifftn
    Compute the N-dimensional invers

и IPython:

In [80]:
np.ar*?

In [82]:
a = np.array([[1, 2], [3, 4]])

In [83]:
a[0, 0] = 100

In [84]:
a

array([[100,   2],
       [  3,   4]])

**Создание массивов**

Создавать из списков мы уже умеем:

In [85]:
x = [1, 2, 3, 4]

In [89]:
np.array([1, 2, 3, 4], dtype=str)

array(['1', '2', '3', '4'], dtype='<U1')

In [90]:
np.arange(100, 1000, 30)

array([100, 130, 160, 190, 220, 250, 280, 310, 340, 370, 400, 430, 460,
       490, 520, 550, 580, 610, 640, 670, 700, 730, 760, 790, 820, 850,
       880, 910, 940, 970])

In [91]:
np.linspace(0, 1, 25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

In [92]:
np.linspace(0, 1, 25, endpoint=False)

array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96])

In [93]:
np.linspace(0, 1, 26)

array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96, 1.  ])

In [97]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [98]:
np.ones(3)

array([1., 1., 1.])

In [99]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [100]:
np.ones((3, 2), 'complex')

array([[1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j]])

In [101]:
A = np.arange(100).reshape(4, 25)

In [102]:
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [103]:
np.ones_like(A)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1]])

In [104]:
np.zeros_like(A)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]])

In [105]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

** Случайные массивы **

на интервале [0,1]:

In [107]:
np.random.rand(3, 2)

array([[0.74476418, 0.586479  ],
       [0.49286785, 0.48735588],
       [0.2667407 , 0.6050111 ]])

Нормально распределенные:

In [110]:
np.random.randn(3, 2)

array([[-0.18294898,  0.2687804 ],
       [ 1.08838784, -0.99145467],
       [ 0.62201559, -1.6552821 ]])

-- N: иногда полезно получить случайное целое число:

In [112]:
np.random.randint(0, 100, (3, 4))

array([[39, 66, 62,  8],
       [53, 69, 47, 48],
       [53, 61, 57, 32]])

In [113]:
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [115]:
A[-1]

4

In [114]:
A = np.arange(5)
print(A)
A[[0, 1, -4]]

[0 1 2 3 4]


array([0, 1, 1])

# 2.2. Numpy ndarray - индексы

Отдельно рассмотрим 1-мерный и многомерные массивы.

In [116]:
t = np.random.rand(3,)

In [117]:
t

array([0.64631507, 0.64181609, 0.38186211])

Для одномерного массива получим сразу элемент, который находится по данному индексу. Для n-мерного массива подобная индексация вернет массив размера n-1.

In [ ]:
t.shape

In [ ]:
t = np.random.rand(3, 5, 10)
t

In [ ]:
t.shape

In [ ]:
t[0, 1, :]

In [ ]:
t[0, 1, 5]

In [ ]:
np.random.rand(3, 5, 10)[1].shape

In [ ]:
np.random.rand(3, 5)[1].shape

Можно использовать ':' вместо индекса:

In [119]:
A = np.random.rand(3, 5)

In [124]:
A

array([[0.64440971, 0.56654912, 0.21585811, 0.16438761, 0.66374542],
       [0.27097684, 0.9657297 , 0.84086538, 0.49909121, 0.27807149],
       [0.54063119, 0.15955146, 0.13580717, 0.41323191, 0.63669498]])

In [125]:
A[:, 2]

array([0.21585811, 0.84086538, 0.13580717])

In [121]:
A[0, :]

array([0.64440971, 0.56654912, 0.21585811, 0.16438761, 0.66374542])

In [ ]:
A[:, 0]

Поддерживается стандартный протокол - python slicing syntax ([lower:upper:step]) :

In [126]:
A[0, :]

array([0.64440971, 0.56654912, 0.21585811, 0.16438761, 0.66374542])

In [127]:
A

array([[0.64440971, 0.56654912, 0.21585811, 0.16438761, 0.66374542],
       [0.27097684, 0.9657297 , 0.84086538, 0.49909121, 0.27807149],
       [0.54063119, 0.15955146, 0.13580717, 0.41323191, 0.63669498]])

In [129]:
A[0, :][0:5:2]

array([0.64440971, 0.21585811, 0.66374542])

In [130]:
a = A[0, :]

In [131]:
a

array([0.64440971, 0.56654912, 0.21585811, 0.16438761, 0.66374542])

Операция slicing создает т.н. view - то есть данные не копируются, поэтому исходный объект по адресу - mutable.

In [132]:
A[0,:][0:4:2]

array([0.64440971, 0.21585811])

In [133]:
A

array([[0.64440971, 0.56654912, 0.21585811, 0.16438761, 0.66374542],
       [0.27097684, 0.9657297 , 0.84086538, 0.49909121, 0.27807149],
       [0.54063119, 0.15955146, 0.13580717, 0.41323191, 0.63669498]])

In [161]:
A[0,:][0:4:2] = [2.0, 3.]

In [149]:
A

array([[2.        , 0.56654912, 2.        , 0.16438761, 0.66374542],
       [0.27097684, 0.9657297 , 0.84086538, 0.49909121, 0.27807149],
       [0.54063119, 0.15955146, 0.13580717, 0.41323191, 0.63669498]])

Параметры для slicing могут пропускаться:

In [163]:
A

array([[2.        , 0.56654912, 3.        , 0.16438761, 0.66374542],
       [0.27097684, 0.9657297 , 0.84086538, 0.49909121, 0.27807149],
       [0.54063119, 0.15955146, 0.13580717, 0.41323191, 0.63669498]])

In [164]:
A[0, :][0:4:2]

array([2., 3.])

In [168]:
A[0, :][0:4:]

array([2.        , 0.56654912, 3.        , 0.16438761])

In [169]:
A[0, :][0:3]

array([2.        , 0.56654912, 3.        ])

In [174]:
A[0, :][2:5]

array([3.        , 0.16438761, 0.66374542])

In [175]:
A[0, :]

array([2.        , 0.56654912, 3.        , 0.16438761, 0.66374542])

In [178]:
A

array([[2.        , 0.56654912, 3.        , 0.16438761, 0.66374542],
       [0.27097684, 0.9657297 , 0.84086538, 0.49909121, 0.27807149],
       [0.54063119, 0.15955146, 0.13580717, 0.41323191, 0.63669498]])

In [180]:
A[:, ::-1]

array([[0.66374542, 0.16438761, 3.        , 0.56654912, 2.        ],
       [0.27807149, 0.49909121, 0.84086538, 0.9657297 , 0.27097684],
       [0.63669498, 0.41323191, 0.13580717, 0.15955146, 0.54063119]])

In [ ]:
A[0, :]

In [181]:
A[0, :][:-3]

array([2.        , 0.56654912])

In [182]:
A[0, :][-3:]

array([3.        , 0.16438761, 0.66374542])

** Fancy Indexing **

Этим термином обозначается индексирование с помощью массивов (или иных итерируемых конструкций).

In [183]:
A

array([[2.        , 0.56654912, 3.        , 0.16438761, 0.66374542],
       [0.27097684, 0.9657297 , 0.84086538, 0.49909121, 0.27807149],
       [0.54063119, 0.15955146, 0.13580717, 0.41323191, 0.63669498]])

In [184]:
row_indices = [1, 2]
A[row_indices]

array([[0.27097684, 0.9657297 , 0.84086538, 0.49909121, 0.27807149],
       [0.54063119, 0.15955146, 0.13580717, 0.41323191, 0.63669498]])

In [185]:
col_indices = [1, -1] # [1, 4]
A[row_indices, col_indices]

array([0.9657297 , 0.63669498])

Возможно Булево индексирование (**Boolean indexing**):

In [189]:
B = np.array([n for n in range(5)])
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [190]:
B

array([0, 1, 2, 3, 4])

In [191]:
B > 2

array([False, False, False,  True,  True])

array([ True, False,  True,  True,  True])

In [199]:
B[(B <= 0) | (B > 2)]

array([0, 3, 4])

In [200]:
np.array([1, 0, 1, 0, 0], dtype=bool)

array([ True, False,  True, False, False])

In [201]:
row_mask = np.array([1, 0, 1, 0, 0], dtype=bool)
B[row_mask]

array([0, 2])

In [202]:
row_mask

array([ True, False,  True, False, False])

In [203]:
B

array([0, 1, 2, 3, 4])

In [204]:
row_mask = np.array([1, 0, 1, 0, 3])
B[row_mask]

array([1, 0, 1, 0, 3])

Это очень удобно, как вы наверняка догадались, если мы хотим отобрать данные, отвечающие определенным условиям:

In [205]:
x = np.arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [206]:
mask = (5 < x) * (x < 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [207]:
mask = (5 < x) & (x < 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [208]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

In [213]:
a = np.array([[1, 2], [3, 4], [4, 5]])

In [214]:
a

array([[1, 2],
       [3, 4],
       [4, 5]])

In [215]:
(a > 1)

array([[False,  True],
       [ True,  True],
       [ True,  True]])

In [216]:
a[a > 2]

array([3, 4, 4, 5])

Получить список индексов элементов, отвечающих заданной маске, можно с помощью **where**:

In [217]:
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [219]:
indices = np.where(mask == True)

indices

(array([11, 12, 13, 14]),)

In [221]:
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [220]:
x[indices]

array([5.5, 6. , 6.5, 7. ])

**take** еще одна конструкция выбора элементов массива:

In [222]:
v = np.arange(-3, 3)
row_indices = [1, 3, 5]

In [223]:
v

array([-3, -2, -1,  0,  1,  2])

In [224]:
v[row_indices]

array([-2,  0,  2])

In [225]:
v.take(row_indices)

array([-2,  0,  2])

In [226]:
np.take(v, row_indices)

array([-2,  0,  2])

## TLDR:
* для доступа к элементам массива пользуйтесь slicing и помните, что slicing создает view, а значит исходный массив может быть изменен.

# 2.3. Numpy ndarray - элементарные операции с массивами

** Broadcasting **

Концепеция broadcasting является ключевой для понимания операций с массивами. Обычно, операции с массивами производятся поэлементно. 

In [227]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])

In [228]:
a / b

array([0.5, 1. , 1.5])

Что, если массивы разного размера? Начнем с простого - скаляр и вектор:

In [229]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

** Операции вида "массив - скаляр" **

In [233]:
A + 2

array([[4.        , 2.56654912, 5.        , 2.16438761, 2.66374542],
       [2.27097684, 2.9657297 , 2.84086538, 2.49909121, 2.27807149],
       [2.54063119, 2.15955146, 2.13580717, 2.41323191, 2.63669498]])

In [236]:
np.eye(3) * 2

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [238]:
np.ones_like(A) * 2

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [239]:
A + np.ones_like(A) * 2

array([[4.        , 2.56654912, 5.        , 2.16438761, 2.66374542],
       [2.27097684, 2.9657297 , 2.84086538, 2.49909121, 2.27807149],
       [2.54063119, 2.15955146, 2.13580717, 2.41323191, 2.63669498]])

** Операции вида "массив - массив" **

Производятся поэлементно с учетом правил broadcasting:

In [240]:
A * A

array([[4.        , 0.3209779 , 9.        , 0.02702329, 0.44055798],
       [0.07342845, 0.93263385, 0.70705459, 0.24909203, 0.07732375],
       [0.29228209, 0.02545667, 0.01844359, 0.17076061, 0.4053805 ]])

In [241]:
A / A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

** Матричные операции**

In [242]:
A = np.random.rand(3,3)

In [243]:
A

array([[0.75065684, 0.17963987, 0.83831931],
       [0.74639169, 0.99270199, 0.03450743],
       [0.94695076, 0.78073814, 0.57290244]])

In [244]:
np.dot(A, A)

array([[1.49141451, 0.96768461, 1.11576421],
       [1.33390538, 1.14648021, 0.67973955],
       [1.83608192, 1.3924372 , 1.14900558]])

In [245]:
A.dot(A)

array([[1.49141451, 0.96768461, 1.11576421],
       [1.33390538, 1.14648021, 0.67973955],
       [1.83608192, 1.3924372 , 1.14900558]])

In [246]:
v = np.random.randn(3)

In [247]:
v

array([-0.29296672, -1.25059518,  0.33315034])

In [248]:
v.shape

(3,)

array([[-0.29296672],
       [-1.25059518],
       [ 0.33315034]])

In [260]:
A = np.arange(9).reshape(-3, 3)

In [261]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [262]:
v = np.arange(3)

In [263]:
v

array([0, 1, 2])

In [264]:
v[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [265]:
A * v

array([[ 0,  1,  4],
       [ 0,  4, 10],
       [ 0,  7, 16]])

In [266]:
A * v[:, np.newaxis]

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [12, 14, 16]])

In [268]:
np.dot(A, v[:, np.newaxis])

array([[ 5],
       [14],
       [23]])

In [267]:
np.dot(A, v)

array([ 5, 14, 23])

In [269]:
v[:, np.newaxis].shape

(3, 1)

In [270]:
np.dot(A, v[:, np.newaxis])

array([[ 5],
       [14],
       [23]])

In [271]:
A.dot(v[:, np.newaxis])

array([[ 5],
       [14],
       [23]])

In [272]:
np.dot(v[np.newaxis, :], A)

array([[15, 18, 21]])

In [273]:
v

array([0, 1, 2])

In [274]:
np.dot(v, v)

5

Если хочется использовать по умолчанию операции из матричной алгебры, то можно использовать конструктор matrix().

In [275]:
M = np.matrix(A)

In [276]:
M

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [277]:
v1 = np.matrix(v).T

In [278]:
M.shape

(3, 3)

In [279]:
v1

matrix([[0],
        [1],
        [2]])

In [280]:
v1.T * v1

matrix([[5]])

In [281]:
M * v1

matrix([[ 5],
        [14],
        [23]])

** Преобразование массивов**

In [282]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [283]:
A.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

** reshape **

In [284]:
a

array([1., 2., 3.])

In [285]:
a = a.reshape((2, 2))

ValueError: cannot reshape array of size 3 into shape (2,2)

In [ ]:
a

In [ ]:
a.reshape(-1, 2)

** resize **

In [304]:
a = np.arange(4)

In [305]:
a

array([0, 1, 2, 3])

In [308]:
a.resize(4, refcheck=False)

In [307]:
a

array([0, 1, 2])

In [291]:
a = np.array([[1, 2], [3, 4]])
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [310]:
a

array([0, 1, 2, 0])

In [311]:
np.tile(a, 3)

array([0, 1, 2, 0, 0, 1, 2, 0, 0, 1, 2, 0])

** concatenate **

In [322]:
a = np.array([[1, 3]])

In [323]:
b = np.array([[5, 6]])

In [324]:
np.concatenate((a, b))

array([[1, 3],
       [5, 6]])

In [325]:
b

array([[5, 6]])

In [326]:
b.T

array([[5],
       [6]])

In [331]:
a

array([[1, 3]])

In [332]:
b

array([[5, 6]])

In [335]:
np.concatenate((a, b), axis=0)

array([[1, 3],
       [5, 6]])

In [336]:
np.concatenate((a, b), axis=1)

array([[1, 3, 5, 6]])

** hstack **

Название говорит само за себя - horizontal stack.

In [343]:
a = np.array([[1], [3]])

In [346]:
a

array([[1],
       [3]])

In [344]:
b.T

array([[5],
       [6]])

In [345]:
np.hstack((a, b.T))

array([[1, 5],
       [3, 6]])

In [347]:
a.shape

(2, 1)

In [348]:
b.T.shape

(2, 1)

** vstack **

In [350]:
a = np.array([2, 3])
b = np.array([4, 5])

In [351]:
np.vstack((a,b))

array([[2, 3],
       [4, 5]])

In [352]:
np.hstack((a,b))

array([2, 3, 4, 5])

In [ ]:
a.shape

In [ ]:
b.shape

** Копии и view **

Мы помним, что очень важно различать копирование объекта и присваивание новой ссылки на объект. Numpy в этом смысле не отличается от списков:

In [353]:
A = np.array([[1, 2], [3, 4]])

In [355]:
A

array([[1, 2],
       [3, 4]])

In [356]:
B = A

In [357]:
B[0, 0] = 10

In [358]:
A

array([[10,  2],
       [ 3,  4]])

Если это не тот тип поведения, который нам нужен - следует использовать np.copy():

In [359]:
A = np.array([[1, 2], [3, 4]])

In [360]:
B = np.copy(A)

In [361]:
B[0, 0] = 100

In [362]:
A

array([[1, 2],
       [3, 4]])

Важно помнить, что если вы используете view массива, то копии вы не создаете!

In [370]:
a = np.arange(10)

In [371]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [372]:
b = a[::2]

In [373]:
np.may_share_memory(a, b)

True

In [374]:
c = a[::2].copy()
np.may_share_memory(a, c)

False

In [381]:
d = a.T
np.may_share_memory(a, d)

True

In [383]:
d[2] = 1000

In [384]:
a

array([ -11,    1, 1000,    3,    4,    5,    6,    7,    8,    9])

In [377]:
b[0] = -11

In [378]:
a

array([-11,   1,   2,   3,   4,   5,   6,   7,   8,   9])

## TLDR:
* следует отличать копию массива и view;
* при осуществлении операций помните про правила broadcasting;
* запомните hstack и vstack.

# 2.4. Numpy - основные функции.

** Встроенные функции массива **

In [396]:
m = np.random.randint(0, 10, (3, 3))

In [397]:
m

array([[0, 6, 2],
       [8, 3, 3],
       [8, 2, 6]])

In [398]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [403]:
m[np.eye(3, dtype=bool)].sum()

9

In [388]:
m.max()

9

In [389]:
m.min()

2

** Всегда используйте встроенные функции! **

In [404]:
a = np.random.rand(1000)

In [406]:
%timeit -n 1000 max(a)

91.3 µs ± 1.98 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [407]:
%timeit -n 1000 a.max()

2.92 µs ± 238 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [408]:
%timeit -n 1000 sum(a)

144 µs ± 761 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [409]:
%timeit -n 1000 a.sum()

2.66 µs ± 378 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Просто считать сумму элементов матрицы или находить максимальный элемент не так интересно, и тут нам помогают axis:

In [410]:
m

array([[0, 6, 2],
       [8, 3, 3],
       [8, 2, 6]])

In [411]:
m.sum(axis=0)

array([16, 11, 11])

In [412]:
m.sum(axis=1)

array([ 8, 14, 16])

In [414]:
m.max(axis=1)

array([6, 8, 8])

Очень полезно произведение всех элементов:

In [418]:
m.prod(axis=1)

array([ 0, 72, 96])

In [419]:
m

array([[0, 6, 2],
       [8, 3, 3],
       [8, 2, 6]])

In [421]:
np.concatenate((m, m), axis=1)

array([[0, 6, 2, 0, 6, 2],
       [8, 3, 3, 8, 3, 3],
       [8, 2, 6, 8, 2, 6]])

In [416]:
m.prod()

0

Кумулятивная сумма элементов:

In [423]:
m

array([[0, 6, 2],
       [8, 3, 3],
       [8, 2, 6]])

In [422]:
m.cumsum()

array([ 0,  6,  8, 16, 19, 22, 30, 32, 38])

Кумулятивное произведение:

In [425]:
m[0, 0] = 1

In [426]:
m.cumprod()

array([    1,     6,    12,    96,   288,   864,  6912, 13824, 82944])

**Простые статистики**

**Среднее**

In [427]:
m

array([[1, 6, 2],
       [8, 3, 3],
       [8, 2, 6]])

In [428]:
m.mean(axis=0)

array([5.66666667, 3.66666667, 3.66666667])

In [429]:
np.mean(m, axis=1)

array([3.        , 4.66666667, 5.33333333])

In [430]:
np.mean(m)

4.333333333333333

In [432]:
m.mean(axis=0)

array([5.66666667, 3.66666667, 3.66666667])

**Медиана**

In [433]:
np.median(m, axis=0)

array([8., 3., 3.])

In [434]:
np.median(m)

3.0

** Дисперсия **

In [435]:
np.std(m, axis=0)

array([3.29983165, 1.69967317, 1.69967317])

In [436]:
m.std(axis=0)

array([3.29983165, 1.69967317, 1.69967317])

In [437]:
np.var(a)

0.08578470527833251

In [438]:
a.var()

0.08578470527833251

** Сортировка **

In [439]:
a = np.random.randint(0, 100, 12)

In [440]:
a

array([33, 76, 48, 95, 31, 45, 38, 14,  1, 24, 39, 63])

In [447]:
sorted(a, reverse=True)

[95, 76, 63, 48, 45, 39, 38, 33, 31, 24, 14, 1]

In [450]:
np.sort(a)[::-1]

array([95, 76, 63, 48, 45, 39, 38, 33, 31, 24, 14,  1])

Функция выше возвращает отсортированную копию массива. Если нужна сортировка in-place:

In [458]:
a = np.random.randint(0, 100, 12)

In [454]:
 np.sort(a)

array([15, 16, 20, 23, 30, 35, 49, 54, 62, 78, 84, 86])

In [455]:
a

array([16, 86, 49, 78, 54, 35, 62, 20, 84, 15, 30, 23])

In [461]:
a = np.random.randint(0, 100, 12)

In [464]:
a

array([61,  4, 55, 94, 45, 95, 20, 74, 62, 70, 54, 18])

In [462]:
np.sort(a)

array([ 4, 18, 20, 45, 54, 55, 61, 62, 70, 74, 94, 95])

In [463]:
a

array([61,  4, 55, 94, 45, 95, 20, 74, 62, 70, 54, 18])

In [465]:
a.sort()

In [466]:
a

array([ 4, 18, 20, 45, 54, 55, 61, 62, 70, 74, 94, 95])

In [ ]:
a = np.random.rand(100)

In [ ]:
a = np.random.randint(0, 100, 120)

In [ ]:
a

Также иногда бывает полезно получить только список индексов в правильном порядке:

In [473]:
a = np.random.randint(0, 10, 10)

In [474]:
a

array([0, 7, 4, 6, 0, 9, 4, 8, 0, 1])

In [475]:
np.argsort(a)

array([0, 4, 8, 9, 2, 6, 3, 1, 7, 5])

In [476]:
a[np.argsort(a)]

array([0, 0, 0, 1, 4, 4, 6, 7, 8, 9])

In [477]:
np.argmax(a)

5

In [478]:
np.argmin(a)

0

In [479]:
a

array([0, 7, 4, 6, 0, 9, 4, 8, 0, 1])

In [481]:
a

array([0, 7, 4, 6, 0, 9, 4, 8, 0, 1])

In [480]:
np.nonzero(a)

(array([1, 2, 3, 5, 6, 7, 9]),)

** Функции для работы с матрицами **

In [482]:
m

array([[1, 6, 2],
       [8, 3, 3],
       [8, 2, 6]])

In [483]:
np.diag(m)

array([1, 3, 6])

In [484]:
m.diagonal()

array([1, 3, 6])

Для целого класса функций из линейной алгебры есть свой суб-модуль np.linalg.

http://docs.scipy.org/doc/numpy/reference/routines.linalg.html

In [485]:
MM = np.random.randn(9, 6)

In [486]:
U, s, V = np.linalg.svd(MM, full_matrices=False)
U.shape, V.shape, s.shape

((9, 6), (6, 6), (6,))

In [487]:
S = np.diag(s)

In [488]:
MM - np.dot(U, np.dot(S, V))

array([[-3.33066907e-16,  8.32667268e-16, -7.77156117e-16,
         1.66533454e-16,  1.99840144e-15, -5.75928194e-16],
       [ 2.56739074e-16, -8.88178420e-16, -4.44089210e-16,
         2.01227923e-16, -1.94289029e-16, -1.66533454e-16],
       [-8.04911693e-16, -1.77635684e-15,  0.00000000e+00,
        -4.44089210e-16,  7.77156117e-16,  2.22044605e-15],
       [-1.11022302e-16, -1.44328993e-15,  1.11022302e-15,
        -1.52655666e-16,  6.66133815e-16, -7.77156117e-16],
       [ 2.22044605e-16,  1.77635684e-15, -4.99600361e-16,
         3.33066907e-16,  0.00000000e+00,  1.11022302e-16],
       [-8.88178420e-16, -7.77156117e-16,  7.77156117e-16,
        -2.77555756e-17, -3.33066907e-16, -1.11022302e-15],
       [-1.77635684e-15, -4.44089210e-16,  4.44089210e-16,
        -4.44089210e-16,  1.22124533e-15,  7.21644966e-16],
       [ 4.44089210e-16,  8.88178420e-16, -5.55111512e-16,
         3.88578059e-16, -1.33226763e-15, -1.55431223e-15],
       [-4.44089210e-16,  1.55431223e-15, -4.440

In [489]:
np.allclose(MM, np.dot(U, np.dot(S, V)))

True

** Векторизация кода **

В numpy есть встроенная функция vectorize, которая "автоматически" векторизует вашу функцию:

In [490]:
a = np.array([-3, -2, -1, 0, 1, 2, 3])

In [491]:
a

array([-3, -2, -1,  0,  1,  2,  3])

In [492]:
def heavyside(x):
    if x >= 0:
        return 1
    else:
        return 0

In [494]:
heavyside(4)

1

In [495]:
heavyside_vec = np.vectorize(heavyside)

In [496]:
heavyside_vec(a)

array([0, 0, 0, 1, 1, 1, 1])

In [493]:
heavyside(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [497]:
def heavyside(x):
    if x%2 == 0:
        return 1
    else:
        return 0

In [498]:
heavyside_vec = np.vectorize(heavyside)

In [499]:
heavyside_vec(np.array([-3, -2, -1, 0, 1, 2, 3]))

array([0, 1, 0, 1, 0, 1, 0])

Тем не менее, лучше сразу пишите так:

In [501]:
def heavyside(x):
    return 1 * (x >= 0)

In [502]:
heavyside(np.array([-3,-2,-1,0,1,2,3]))

array([0, 0, 0, 1, 1, 1, 1])

In [503]:
np.array([-3,-2,-1,0,1,2,3]) >= 0

array([False, False, False,  True,  True,  True,  True])

In [504]:
1 * (np.array([-3,-2,-1,0,1,2,3]) >= 0)

array([0, 0, 0, 1, 1, 1, 1])

** Условные выражения **

Как вы уже поняли, для вектора конструкция типа if (vector) не подходит.

In [505]:
M

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [509]:
i = 7
if (M > i).any():
    print("at least one element in M is larger than {}".format(i))
else:
    print("no element in M is larger than {}".format(i))

at least one element in M is larger than 7


In [512]:
if (M > -1).all():
    print("all elements in M are larger than -1")
else:
    print("all elements in M are not larger than -1")

all elements in M are larger than -1


## TLDR:
- всегда используйте встроенные в np функции;
- векторизуйте везде, где это возможно!

# 2.5. Numpy - I/O.

В данном случае у нас на выбор 2 опции - либо формат numpy, либо просто текстовый файл.

In [513]:
!ls

Black_man.txt  frame.csv.gz  matplotlib.ipynb  pandas.ipynb  random.npy
frame.csv      HW1.ipynb     numpy.ipynb       random.csv


In [520]:
np.save("random123.npy", M)

In [521]:
!ls

Black_man.txt  frame.csv.gz  matplotlib.ipynb  pandas.ipynb   random.csv
frame.csv      HW1.ipynb     numpy.ipynb       random123.npy  random.npy


In [ ]:
!cat Black_man.txt | head -9

In [522]:
N = np.load("random.npy")

In [524]:
np.savetxt('random_txt.csv', M, delimiter='\t')

In [526]:
! cat random_txt.csv

0.000000000000000000e+00	1.000000000000000000e+00	2.000000000000000000e+00
3.000000000000000000e+00	4.000000000000000000e+00	5.000000000000000000e+00
6.000000000000000000e+00	7.000000000000000000e+00	8.000000000000000000e+00


In [528]:
np.loadtxt('random_txt.csv')

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

# А теперь задачки!

In [529]:
(np.arange(100))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [530]:
(lambda x: x + 1)(np.arange(100))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [531]:
lambda x, y: x + y

<function __main__.<lambda>(x, y)>

In [532]:
_(1, 2)

3

In [534]:
lambda x, y: x * y

<function __main__.<lambda>(x, y)>

In [535]:
_(1, 2)

2

#### Написать функцию, которая поможет развернуть все слова в строке:

In [536]:
s = "Hello world"

In [541]:
s

'Hello world'

In [544]:
s[::-1].split()[::-1]

['olleH', 'dlrow']

In [547]:
" ".join(s[::-1].split()[::-1])

'olleH dlrow'

In [ ]:
olleH dlrow

#### Написать функцию, которая определяет является ли число палиндромом

In [549]:
x1 = 126567654
x2 = 12345654321

In [550]:
def is_palindrom(x):
    return str(x) == str(x)[::-1]

In [551]:
is_palindrom(x1)

False

In [552]:
is_palindrom(x2)

True

#### Сложите цифры целого числа

In [554]:
list(str("Hello"))

['H', 'e', 'l', 'l', 'o']

In [553]:
a = 126567654

In [559]:
def summarize(a):
    return np.sum(np.array(list(str(a))).astype(int))

In [560]:
summarize(a)

42

#### Извлеките из массива числа, делимые на 15.

In [563]:
nums = np.array([45, 55, 60, 37, 100, 105, 220])

In [566]:
def dev_15(ar):
    return ar[ar%15 == 0]

In [568]:
nums % 15

array([ 0, 10,  0,  7, 10,  0, 10])

In [567]:
dev_15(nums)

array([ 45,  60, 105])

#### Напишите программу, которая принимает текст и выводит два слова: наиболее часто встречающееся и самое длинное.

In [569]:
with open('./Black_man.txt') as f:
    black = f.readlines()

In [571]:
lower = (" ".join(black).lower())

In [573]:
only_letters = ""
for i in lower:
    if (i >= "а" and i <= "я") or i in [" ", "\n"]:
        only_letters += i

In [576]:
only_letters = only_letters.replace("\n", " ")

In [577]:
x = only_letters.split()

In [578]:
l = [len(i) for i in x]

#### Напишите функцию, которая создаёт комбинацию двух списков таким образом:

[1, 2, 3] (+) [11, 22, 33] -> [1, 11, 2, 22, 3, 33]

In [608]:
x = [1, 2, 3, -1]
y = [11, 22, 33, 1123]

In [620]:
def union(a, b):
    x = np.zeros(len(a) + len(b), dtype=int)
    x[0::2] = a
    x[1::2] = b
    return x

In [605]:
x = np.zeros(len(x) + len(y))

In [606]:
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [621]:
union(x, y)

array([   1,   11,    2,   22,    3,   33,   -1, 1123])

#### Написать функцию, которая удаляет лишние пробелы в строке

In [622]:
x = "I   Love        Python"

In [623]:
def delete_spaces(string):
    return " ".join(x.split())

In [624]:
delete_spaces(x)

'I Love Python'

In [ ]:
%timeit delete_spaces_optimal(lower)

In [ ]:
%timeit delete_spaces(lower)